### ISSUE TITLE
Practica 2

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo_eaaj#1]
[Practica2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo_eaaj/files/14301257/Practica2.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 95
Su reporte esta bien estructurado e incluye todos los criterios de la rubrica solo les falto colocar su indice de contenidos.

**Comment by Kim-Mendoza3** [comment]
Calificacion 95
Su reporte esta bien estructurado e incluye todos los criterios de la rubrica solo les falto colocar su indice de contenidos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
